### ISSUE TITLE
HierarchyID is not supported

### ISSUE THREAD

**Issue by isaacabraham** [cmeeren/Facil#16]
Using the standard AdventureWorks sample DB (I think I got it from [here](https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver15&tabs=ssms)), trying to run Facil gives the following error:

```
   ---> System.Exception: Unsupported SQL system type ID '240' for column 'OrganizationNode' in table 'Employee'
     at Facil.Db.typeInfo@736-9.Invoke(Unit unitVar0) in C:\projects\facil\src\Facil.Generator\Db.fs:line 736
     at Facil.Db.getTableDtos(RuleSet cfg, FSharpMap`2 sysTypeIdLookup, FSharpMap`2 primaryKeyColumnNamesByTable, SqlConnection conn) in C:\projects\facil\src\Facil.Generator\Db.fs:line 730
     --- End of inner exception stack trace ---
     at Facil.Db.getTableDtos(RuleSet cfg, FSharpMap`2 sysTypeIdLookup, FSharpMap`2 primaryKeyColumnNamesByTable, SqlConnection conn) in C:\projects\facil\src\Facil.Generator\Db.fs:line 799
     at Facil.Db.getEverything(RuleSet cfg, String fullYamlPath, FSharpList`1 scriptsWithoutParamsOrResultSetsOrTempTables, SqlConnection conn) in C:\projects\facil\src\Facil.Generator\Db.fs:line 856
     at Facil.Program.regenerate@108(String yamlFilePath, RuleSet cfg, FSharpList`1 scriptsWithoutParamsOrResultSetsOrTempTables, String hash, String outFile, Unit unitVar0) in C:\projects\facil\src\Facil.Generator\Program.fs:line 117
     at Facil.Program.main(String[] argv) in C:\projects\facil\src\Facil.Generator\Program.fs:line 170
```

This appears to be a SQL type called [HierarchyId](https://docs.microsoft.com/en-us/sql/t-sql/data-types/hierarchyid-data-type-method-reference?view=sql-server-ver15).

Perhaps from a practical point of view, it would be best to have Facil simply warn and not generate tables that contains types that it does not support, but continue with the remaining ones? I'm thinking people would still benefit even if e.g. 90% of their DB could be generated and 10% had to be hand-rolled.

**Comment by isaacabraham** [comment]
Also the `geography` type has the same issue.

**Comment by cmeeren** [comment]
These are deliberately not supported. You can easily skip th
ese columns in the config file. Here's part of the config reference:

https://github.com/cmeeren/Facil/blob/bf8a2597d428e43b313f6337f339b9d89f726320/facil_reference.yaml#L140-L149

**Comment by isaacabraham** [comment]
I believe that there is a Geography type in some of the MS SQL libraries - I believe it's [this one](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.types.sqlgeography?view=sql-dacfx-150). I think HierarchyId is also included in that.

Of course, that could potentially mean a dependency on that library for Facil, which you may not wish to do.

**Comment by cmeeren** [comment]
Thanks for the notice.

I'll leave these types unsupported for now until someone actually needs them.
